version: '3'

services:
  envoy:
    build:
      context: .
      dockerfile: envoy.Dockerfile
    ports:
      - '9090:9090'
      - '9901:9901'
    networks:
      - server-net
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - '45654:45654'
    networks:
      - server-net

networks:
  server-net: