name: client_template
description: client flutter application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  auto_route: ^7.8.4
  cupertino_icons: ^1.0.2
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  firebase_ui_auth: ^1.10.0
  firebase_ui_localizations: ^1.10.0
  firebase_ui_oauth_google: ^1.2.14
  google_sign_in: ^6.1.1
  cloud_firestore: ^4.11.0
  firebase_storage: ^11.5.6
  api:
    path: ../api
  injectable: ^2.3.2
  get_it: ^7.6.4
  grpc: ^3.2.4
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_presentation: ^1.0.0
  meta: ^1.9.0
  google_fonts: ^6.1.0
  device_info_plus: ^9.1.1
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
