name: app
description: fWish app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.11.0
  firebase_storage: ^11.5.6
  api:
    path: ../api
  injectable: ^2.3.2
  get_it: ^7.6.4
  grpc: ^3.2.4
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  meta: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
